# LLM_TYPE (factory/llms.py)
BASIC_MODEL:
  api_key: $BASIC_MODEL_API_KEY
  base_url: https://ark.cn-beijing.volces.com/api/v3
  model: doubao-1-5-pro-256k-250115


REASONING_MODEL:
  api_key: $REASONING_MODEL_API_KEY
  base_url: https://ark.cn-beijing.volces.com/api/v3
  model: doubao-1-5-thinking-pro-250415


VISION_MODEL:
  api_key: $VISION_MODEL_API_KEY
  base_url: https://ark.cn-beijing.volces.com/api/v3
  model: doubao-1.5-vision-pro-250328


# EMBEDDING_TYPE (factory/embeddings.py)
EMBEDDING_MODEL:
  api_key: $EMBEDDING_MODEL_API_KEY
  base_url: https://ark.cn-beijing.volces.com/api/v3
  model: doubao-embedding-vision-241215
