# model configuration
llm_model:
  provider: openai # litellm provider 
  model: qwen3-235b-a22b
  enable_thinking: false
  api_key: ${OPENAI_API_KEY}
  api_base: ${OPENAI_BASE_URL}


embedding_model:
  model: text-embedding-3
  dimension: 1024
  api_key: ${EMBEDDING_API_KEY}
  api_base: ${EMBEDDING_API_BASE}


rerank_model:
  model: gte-rerank 
  api_key: ${RERANK_API_KEY}
  api_base: ${RERANK_API_BASE}


# database configuration 
vector_db:
  type: lancedb # optional: lancedb
  persistent_path: .local_db

# agent configuration
coder_agent:
  sandbox_type: e2b # optional: e2b, sandboxfusion 
  api_key: ${E2B_API_KEY}
  api_base: ${SANDBOX_FUSION_API_BASE}
  
